### ISSUE TITLE
Data for the book

### ISSUE THREAD

**Issue by uzawadzka** [Python-GIS-book/site#154]
The book is great (although under construction) but is there any possibility of getting some data from the list below):
 - pt_stops_helsinki.gpkg
 - building_points_helsinki.zip
 - uusimaa_intersections.gpkg
 - uusimaa_postal_code_areas.gpkg

**Comment by davewhipp** [comment]
Are you able to help with this issue @HTenkanen ?

**Comment by HTenkanen** [comment]
Due to restructuring of the book, the datasets were in a bit different place than originally. Thanks for asking @uzawadzka! In the next release, these should be easy to find. Currently, you should be able to locate the files from the `develop` branch here: https://github.com/Python-GIS-book/site/tree/develop/source/part2/chapter-06/nb/data/Helsinki
